#!/usr/bin/env node
var program = require('commander');

program
    .version('0.0.1')
    .command('init', 'instialize amz monitor in this directory')

    .command('fetch', 'bring latest data from amazon')
    .command('diff [asin]', 'check changes in that book')

    .command('ls', 'list monitored titles')
    .command('add [asin] [title]', 'add a title to monitor')
    .command('rm [asin]', 'removes a title to monitor')
    .parse(process.argv);
