#!/usr/bin/sh

die () {
    echo >&2 "Error: $@"
    exit 1
}

VERBOSE=1
while getopts ":s" opt; do
  case $opt in
      s)
          VERBOSE=0
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

shift $((OPTIND-1))

[ $# -lt 1 ] && die "best [asin]"

[ ! -e .amz/idx/$1 ] && die "unknown asin ($1). List known asins with 'ls'."

[[ $VERBOSE -eq 1 ]] && echo "Historical min for" $(cat .amz/idx/$1) " (asin: $1)"

CURRENT_HEAD=$(cat .amz/refs/$1)

rm -f .tmp-best
while [ $CURRENT_HEAD != "0" ]; do
    FINAL_PRICE=$(cat .amz/objects/$CURRENT_HEAD  | jq -r '.entries[0]' | node ./lib/jsonFormPrice.js)
    DATE=$(cat .amz/objects/$CURRENT_HEAD  | jq -r '.date')
    echo "$FINAL_PRICE $DATE" >> .tmp-best
    
    PREVIOUS_HEAD=$(cat .amz/objects/$CURRENT_HEAD | jq '.parent' --raw-output)
    CURRENT_HEAD=$PREVIOUS_HEAD
done

cat .tmp-best | sort -k1n -k7nr -k3Mr -k4nr | head -1
