#!/usr/bin/sh

die () {
    echo >&2 "Error: $@"
    exit 1
}

[ $# -ne 1 ] && die "diff [asin]"

[ ! -e .amz/idx/$1 ] && die "unknown asin ($1). List known asins with 'ls'."

echo "Results for:" $(cat .amz/idx/$1) " (asin: $1)"
CURRENT_HEAD=$(cat .amz/refs/$1)

PREVIOUS_HEAD=$(cat .amz/objects/$CURRENT_HEAD | jq '.parent' --raw-output)
PREVIOUS_FILE=.amz/objects/$PREVIOUS_HEAD

node ./lib/jsondiff $PREVIOUS_FILE .amz/objects/$CURRENT_HEAD
