#!/usr/bin/sh
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

VERBOSE=1
while getopts ":s" opt; do
  case $opt in
      s)
          VERBOSE=0
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
  shift
done

ASINS=
if [ $# -gt 0 ]; then
    for asin in "$@" ; do
        if [ -e .amz/idx/$asin ]; then
            ASINS="$ASINS $asin";
        else
            echo "Skipping $asin (.amz/idx/$asin doesn't exist)"
        fi
    done
else
    ASINS=$(ls .amz/idx)
fi

for SIMPLE_ASIN in $ASINS ; do
    
    echo "Fetching $SIMPLE_ASIN ("$(cat .amz/idx/$SIMPLE_ASIN)")"
    ./lib/amzPage2json.js $SIMPLE_ASIN > x.json
    [ $? -ne 0 ] && echo "Something wrong processing the amazon page. Skipping." && continue

    #cat x.html | ./lib/json2tab.js > x.tmp
    md5=`md5sum x.json | awk '{ print $1 }'`

    if [ ! -e .amz/refs/$SIMPLE_ASIN ]; then
        previous_md5=$(cat .amz/refs/null)
    else
        previous_md5=$(cat .amz/refs/$SIMPLE_ASIN)
    fi

    if [ $md5 != $previous_md5 ]; then
        cat x.json | jq --arg parent $previous_md5 --arg date "$(date)" \
                        '{ entries: . , parent: $parent, date: $date }' \
                        > .amz/objects/$md5
        #echo "Parent: $previous_md5" > .amz/objects/$md5
        #echo "Date :" $(date) >> .amz/objects/$md5
        #cat x.json >> .amz/objects/$md5
        echo $md5 > .amz/refs/$SIMPLE_ASIN

        [[ $VERBOSE -eq 1 ]] && echo -n "Best price seen: " && $DIR/amz-best -s $SIMPLE_ASIN
        [[ $VERBOSE -eq 1 ]] && $DIR/amz-diff $SIMPLE_ASIN
    fi

    rm -f x.html x.tmp
done
