#!/usr/bin/sh
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

die () {
    echo >&2 "Error: $@"
    exit 1
}

VERBOSE=1
DRYRUN=0
while getopts ":sn" opt; do
  case $opt in
      s)
          VERBOSE=0
          ;;
      n)
          DRYRUN=1
          ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

shift $((OPTIND-1))

[ $# -lt 1 ] && die "best [asin]"

[ ! -e .amz/idx/$1 ] && die "unknown asin ($1). List known asins with 'ls'."

[[ $VERBOSE -eq 1 ]] && echo "Historical min for" $(cat .amz/idx/$1) " (asin: $1)"


[ -e .amz/best-price/$1 ] && cat .amz/best-price/$1 && exit 0
[[ $VERBOSE -eq 1 ]] && echo "No cache, full calculation"

BEST_PRICE=$($DIR/amz-history -s $1 | sort -k1n -k7nr -k3Mr -k4nr | head -1)
echo $BEST_PRICE

[ $DRYRUN -eq 0 ] && echo "$BEST_PRICE" > .amz/best-price/$1
